# Generated by Django 4.1.7 on 2023-06-24 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_representation', models.CharField(max_length=100)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('discount_absolute', models.IntegerField(blank=True, null=True)),
                ('activation_count', models.IntegerField(default=0)),
                ('max_activation_count', models.IntegerField(default=1)),
                ('active_status', models.BooleanField(default=True)),
                ('active_until_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
