# Generated by Django 4.1.7 on 2023-07-27 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonuses',
            name='accrual',
            field=models.ManyToManyField(blank=True, related_name='bonuses', to='promotions.accrualbonus'),
        ),
    ]