# Generated by Django 4.1.7 on 2023-04-06 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='active_until_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_absolute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
