# Generated by Django 4.1.7 on 2023-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promocode_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='ref_promo',
            field=models.BooleanField(default=False),
        ),
    ]
