# Generated by Django 4.1.7 on 2024-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_accrualbonus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='skip_payment',
            field=models.BooleanField(default=False),
        ),
    ]
