# Generated by Django 4.1.7 on 2024-05-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_promocode_skip_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promo_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
