# Generated by Django 4.1.7 on 2023-06-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_is_main_color_line_brand_and_more'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistunit',
            name='size',
        ),
        migrations.AlterField(
            model_name='wishlistunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_units', to='products.product'),
        ),
        migrations.AlterField(
            model_name='wishlistunit',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_units', to='wishlist.wishlist'),
        ),
    ]
