# Generated by Django 4.1.7 on 2023-06-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistunit',
            name='size',
        ),
    ]
