# Generated by Django 4.1.7 on 2023-04-06 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sizetranslationrows_rename_brand_product_brands_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='size',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='wishlist', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WishlistUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_units', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_units', to='products.size')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlist_units', to='wishlist.wishlist')),
            ],
        ),
    ]
