# Generated by Django 4.1.7 on 2023-06-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_line_brand'),
        ('wishlist', '0002_remove_wishlistunit_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_units', to='products.product'),
        ),
        migrations.AlterField(
            model_name='wishlistunit',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_units', to='wishlist.wishlist'),
        ),
    ]
