# Generated by Django 4.1.7 on 2023-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_viewed_products',
        ),
        migrations.AddField(
            model_name='user',
            name='last_viewed_products',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
