# Generated by Django 4.1.7 on 2023-04-06 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_productunit_unit_bundle_and_more'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.gender'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(related_name='users', to='shipping.addressinfo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_size_grid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
