# Generated by Django 4.1.7 on 2023-08-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_sizerow_remove_sizetable_size_rows_and_more'),
        ('users', '0002_remove_user_last_viewed_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clothes_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_with_clothes_size', to='products.sizetranslationrows'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=175),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_clothes_size_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_with_clothes_table', to='products.sizerow'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_shoes_size_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_with_shoes_table', to='products.sizerow'),
        ),
        migrations.AddField(
            model_name='user',
            name='shoes_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_with_shoes_size', to='products.sizetranslationrows'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=60),
        ),
    ]
