# Generated by Django 4.1.7 on 2023-04-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_remove_productunit_unit_bundle_and_more'),
        ('users', '0003_remove_user_wishlist_user_gender_alter_gender_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='shipping.addressinfo'),
        ),
    ]
