# Generated by Django 4.1.7 on 2023-08-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promocode_discount_absolute_and_more'),
        ('users', '0004_rename_preferred_clothes_size_table_user_preferred_clothes_size_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bonuses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='promotions.bonuses'),
        ),
    ]
