# Generated by Django 4.1.7 on 2023-08-18 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_headerphotos_headertext_and_more'),
        ('users', '0005_alter_user_bonuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clothes_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_clothes_size', to='products.sizetranslationrows'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_clothes_size_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_clothes_table', to='products.sizerow'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_shoes_size_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_shoes_table', to='products.sizerow'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='shoes_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_shoes_size', to='products.sizetranslationrows'),
        ),
    ]
