# Generated by Django 4.1.7 on 2023-08-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_productunit_dimensions'),
        ('users', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wait_list',
            field=models.ManyToManyField(blank=True, related_name='wait_list_users', to='shipping.productunit'),
        ),
    ]
