# Generated by Django 4.1.7 on 2023-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_rename_products_configurationunit_product'),
        ('users', '0012_remove_user_wait_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wait_list',
            field=models.ManyToManyField(blank=True, related_name='wait_list_users', to='shipping.configurationunit'),
        ),
    ]
