# Generated by Django 4.1.7 on 2023-09-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
