# Generated by Django 4.1.7 on 2023-09-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_happy_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=128)),
                ('total_orders_amount', models.IntegerField(default=0)),
                ('unit_bonuses', models.IntegerField(default=250)),
                ('free_ship_amount', models.IntegerField(default=20000)),
                ('exclusive_sale', models.BooleanField(default=False)),
                ('close_release', models.BooleanField(default=False)),
                ('priority_service', models.BooleanField(default=False)),
                ('birthday_gift', models.BooleanField(default=True)),
                ('start_bonuses', models.BooleanField(default=True)),
            ],
        ),
    ]
