# Generated by Django 4.1.7 on 2023-09-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_status',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='base',
            field=models.BooleanField(default=True),
        ),
    ]
