# Generated by Django 4.1.7 on 2023-09-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='unit_bonuses',
            new_name='unit_max_bonuses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_status',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='percentage_bonuses',
            field=models.IntegerField(default=10),
        ),
    ]
