# Generated by Django 4.1.7 on 2023-09-08 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_unit_bonuses_userstatus_unit_max_bonuses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userstatus'),
        ),
    ]
