# Generated by Django 4.1.7 on 2023-09-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_user_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userstatus'),
        ),
    ]
