# Generated by Django 4.1.7 on 2023-09-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_promocode_unlimited'),
        ('users', '0024_user_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promocode'),
        ),
    ]
