# Generated by Django 4.1.7 on 2023-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_referral_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_ref_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
