# Generated by Django 4.1.7 on 2023-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_total_ref_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tg', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('chanels', models.CharField(max_length=2000)),
                ('other', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SpamEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
