# Generated by Django 4.1.7 on 2023-10-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_user_extra_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_email',
            field=models.BooleanField(default=True),
        ),
    ]
