# Generated by Django 4.1.7 on 2023-12-04 14:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_referral_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_data',
            field=models.JSONField(default=users.models.default_referral_data),
        ),
    ]
