# Generated by Django 4.1.7 on 2024-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_user_referral_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_data',
            field=models.JSONField(default=dict),
        ),
    ]
