# Generated by Django 4.1.7 on 2024-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_user_referral_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
