# Generated by Django 4.1.7 on 2023-04-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sizetranslationrows_rename_brand_product_brands_and_more'),
        ('utils', '0002_alter_roublerate_currency'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='unit_bundle',
        ),
        migrations.AddField(
            model_name='productunit',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='delivery_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='shipping.deliverytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='final_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='shipping.platform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productunit',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='products.size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formula',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='delivery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='shipping.deliverytype'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='rounding_step',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='platform',
            name='site',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='UnitBundle',
        ),
    ]
