# Generated by Django 4.1.7 on 2023-06-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='view_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
