# Generated by Django 4.1.7 on 2023-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_productunit_good_size_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
