# Generated by Django 4.1.7 on 2023-04-07 15:40

from django.db import migrations, models
import django.db.models.deletion
import shipping.models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_roublerate_currency'),
        ('shipping', '0002_remove_productunit_unit_bundle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='currency',
            field=models.ForeignKey(default=shipping.models.get_default_currency, on_delete=django.db.models.deletion.CASCADE, to='utils.currency'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='delivery_type',
            field=models.ForeignKey(default=shipping.models.get_default_delivery_type, on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='shipping.deliverytype'),
        ),
    ]
