# Generated by Django 4.1.7 on 2023-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_addressinfo_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='history_price',
            field=models.JSONField(default=list),
        ),
    ]
