# Generated by Django 4.1.7 on 2023-08-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_headerphotos_headertext_and_more'),
        ('shipping', '0006_productunit_history_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='delivery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='shipping.deliverytype'),
        ),
    ]
