# Generated by Django 4.1.7 on 2023-08-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_alter_formula_brand_alter_formula_delivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productunit',
            old_name='good_size_platform',
            new_name='view_size_platform',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='size_table_platform',
        ),
    ]
