# Generated by Django 4.1.7 on 2023-08-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_rename_good_size_platform_productunit_view_size_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='dimensions',
            field=models.JSONField(default=dict),
        ),
    ]
