# Generated by Django 4.1.7 on 2023-08-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_ransomrequest'),
        ('shipping', '0009_productunit_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_units', to='products.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_units', to='products.sizetranslationrows')),
            ],
        ),
    ]
