# Generated by Django 4.1.7 on 2023-08-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_configurationunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationunit',
            old_name='products',
            new_name='product',
        ),
    ]
