# Generated by Django 4.1.7 on 2023-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_rename_products_configurationunit_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
