# Generated by Django 4.1.7 on 2023-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0013_alter_addressinfo_post_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytype',
            old_name='days',
            new_name='days_max',
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='days_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productunit',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
