# Generated by Django 4.1.7 on 2023-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0020_alter_productunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='final_price',
            field=models.IntegerField(db_index=True),
        ),
    ]
