# Generated by Django 4.1.7 on 2023-09-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_product_min_price_without_sale'),
        ('shipping', '0021_alter_productunit_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='size',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='product_units', to='products.sizetranslationrows'),
        ),
    ]
