# Generated by Django 4.1.7 on 2023-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0024_productunit_absolute_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='extra_delivery_price',
            field=models.IntegerField(default=0),
        ),
    ]
