# Generated by Django 4.1.7 on 2023-09-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0026_deliverytype_absolute_insurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='extra_delivery_price',
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='extra_charge',
            field=models.IntegerField(default=0),
        ),
    ]
