# Generated by Django 4.1.7 on 2023-09-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0029_deliverytype_poizon_abroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='delivery_type',
            field=models.CharField(default='Стандарт', max_length=64),
        ),
    ]
