# Generated by Django 4.1.7 on 2023-09-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0030_deliverytype_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='delivery_type',
            field=models.CharField(default='standard', max_length=64),
        ),
    ]
