# Generated by Django 4.1.7 on 2023-09-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_product_actual_price_alter_product_bucket_link'),
        ('shipping', '0031_alter_deliverytype_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='size',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='product_units', to='products.sizetranslationrows'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='size_table',
            field=models.ManyToManyField(blank=True, related_name='product_units', to='products.sizetable'),
        ),
    ]
