# Generated by Django 4.1.7 on 2023-09-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0033_productunit_bonus_productunit_total_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='availability',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
