# Generated by Django 4.1.7 on 2023-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_product_content_sources'),
        ('shipping', '0034_alter_productunit_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='size_table',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='product_units', to='products.sizetable'),
        ),
    ]
