# Generated by Django 4.1.7 on 2023-10-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0077_alter_line_full_eng_name'),
        ('shipping', '0037_alter_productunit_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productunit',
            name='shipping_pr_product_98e056_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productunit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='approximate_price_with_delivery_in_rub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='product_units', to='products.sizetranslationrows'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='size_table',
            field=models.ManyToManyField(blank=True, related_name='product_units', to='products.sizetable'),
        ),
    ]
