# Generated by Django 4.1.7 on 2023-10-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0077_alter_line_full_eng_name'),
        ('shipping', '0038_remove_productunit_shipping_pr_product_98e056_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='availability',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='size',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='product_units', to='products.sizetranslationrows'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='size_table',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='product_units', to='products.sizetable'),
        ),
    ]
