# Generated by Django 4.1.7 on 2023-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0041_remove_productunit_shipping_pr_product_98e056_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='weight_kg',
            field=models.FloatField(default=1.0),
        ),
    ]
