# Generated by Django 4.1.7 on 2023-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0041_remove_productunit_shipping_pr_product_98e056_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
