# Generated by Django 4.1.7 on 2024-02-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0043_productunit_update_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
