# Generated by Django 4.1.7 on 2023-07-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promocode_discount_absolute_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='final_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='promotions.promocode'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
