# Generated by Django 4.1.7 on 2023-04-06 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promocode_active_until_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0002_remove_productunit_unit_bundle_and_more'),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promocode',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product_unit',
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='promotions.promocode'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product_units',
            field=models.ManyToManyField(blank=True, related_name='shopping_carts', to='shipping.productunit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.addressinfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.productunit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
