# Generated by Django 4.1.7 on 2023-07-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_addressinfo_is_main'),
        ('products', '0005_alter_product_available_flag_alter_product_brands_and_more'),
        ('orders', '0003_shoppingcart_final_amount_shoppingcart_promo_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_units',
        ),
        migrations.AddField(
            model_name='order',
            name='final_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_size_platform', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('size_table_platform', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('configuration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('start_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('warehouse', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('is_fast_shipping', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units', to='shipping.deliverytype')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units', to='shipping.platform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_units',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.orderunit'),
        ),
    ]
