# Generated by Django 4.1.7 on 2023-04-07 15:40

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_promocode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=orders.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.status'),
        ),
    ]
