# Generated by Django 4.1.7 on 2023-07-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_product_units_order_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='bonus_sale',
            field=models.IntegerField(default=0),
        ),
    ]
