# Generated by Django 4.1.7 on 2023-07-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_shoppingcart_promo_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_sale',
            field=models.IntegerField(default=0),
        ),
    ]
