# Generated by Django 4.1.7 on 2023-08-03 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 13, 0, 17, 444733, tzinfo=datetime.timezone.utc)),
        ),
    ]
