# Generated by Django 4.1.7 on 2023-08-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_sale',
            field=models.IntegerField(default=0),
        ),
    ]
