# Generated by Django 4.1.7 on 2023-08-18 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0003_alter_promocode_discount_absolute_and_more'),
        ('orders', '0013_order_total_sale_shoppingcart_total_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='promotions.promocode'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
