# Generated by Django 4.1.7 on 2023-08-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_shoppingcart_promo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_units', to='orders.status'),
        ),
    ]
