# Generated by Django 4.1.7 on 2023-08-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status_alter_orderunit_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrderUnit',
        ),
    ]
