# Generated by Django 4.1.7 on 2023-08-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_units', to='orders.status'),
        ),
    ]
