# Generated by Django 4.1.7 on 2023-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_status_alter_orderunit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='cancel_reason',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
