# Generated by Django 4.1.7 on 2023-08-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_cancel_order_cancel_reason_orderunit_cancel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderunit',
            old_name='good_size_platform',
            new_name='view_size_platform',
        ),
    ]
