# Generated by Django 4.1.7 on 2023-08-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_rename_good_size_platform_orderunit_view_size_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tel',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='patronymic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
