# Generated by Django 4.1.7 on 2023-08-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_rename_tel_order_phone_order_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='unit_order',
            field=models.JSONField(default=list),
        ),
    ]
