# Generated by Django 4.1.7 on 2023-09-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0017_productunit_weight'),
        ('orders', '0024_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='groups_delivery',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='pvz',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.addressinfo'),
        ),
    ]
