# Generated by Django 4.1.7 on 2023-09-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_orderunit_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
