# Generated by Django 4.1.7 on 2023-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_delivery_view_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_amount_without_shipping',
            field=models.IntegerField(default=0),
        ),
    ]
