# Generated by Django 4.1.7 on 2023-09-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_final_amount_without_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='status',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_units', to='orders.status'),
        ),
    ]
