# Generated by Django 4.1.7 on 2023-09-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_order_pvz_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='total_profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orders', to='orders.status'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='status',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_units', to='orders.status'),
        ),
    ]
