# Generated by Django 4.1.7 on 2023-09-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_orderunit_bonus_orderunit_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='track_number',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
