# Generated by Django 4.1.7 on 2023-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_order_track_numbers_orderunit_track_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pvz',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='pvz_address',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
