# Generated by Django 4.1.7 on 2023-10-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_shoppingcart_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='first_order_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
