# Generated by Django 4.1.7 on 2023-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_order_order_in_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_int',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
