# Generated by Django 4.1.7 on 2023-10-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_order_phone_int_alter_order_name_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
