# Generated by Django 4.1.7 on 2023-11-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_order_invoice_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderunit',
            old_name='size_table_platform',
            new_name='size_platform',
        ),
    ]
