# Generated by Django 4.1.7 on 2023-11-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_rename_size_table_platform_orderunit_size_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderunit',
            name='weight',
        ),
        migrations.AddField(
            model_name='orderunit',
            name='weight_kg',
            field=models.FloatField(default=1),
        ),
    ]
