# Generated by Django 4.1.7 on 2023-11-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_remove_orderunit_weight_orderunit_weight_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderunit',
            old_name='weight_kg',
            new_name='weight',
        ),
    ]
