# Generated by Django 4.1.7 on 2023-11-12 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_rename_weight_kg_orderunit_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_of_buy_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
