# Generated by Django 4.1.7 on 2023-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_order_date_of_buy_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
