# Generated by Django 4.1.7 on 2023-12-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_order_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_accrue_bonuses',
            field=models.BooleanField(default=False),
        ),
    ]
