# Generated by Django 4.1.7 on 2023-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_order_is_accrue_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_bonus_and_promo_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
