# Generated by Django 4.1.7 on 2024-03-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_order_total_bonus_and_promo_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='on_way_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
