# Generated by Django 4.1.7 on 2024-07-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_shoppingcart_delivery_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_day_to_client',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='delivery_date_str',
            field=models.CharField(default='', max_length=127),
        ),
    ]
