# Generated by Django 4.1.7 on 2023-07-27 22:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('query_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eng_name', models.CharField(default='', max_length=255)),
                ('is_all', models.BooleanField(default=False)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('query_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_main_collab', models.BooleanField(default=False)),
                ('is_all', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_collab', models.BooleanField(default=False)),
                ('in_filter', models.BooleanField(default=False)),
                ('query_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_main_color', models.BooleanField(default=False)),
                ('russian_name', models.CharField(default='', max_length=255)),
                ('hex', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_all', models.BooleanField(default=False)),
                ('view_name', models.CharField(default='', max_length=255)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('full_eng_name', models.CharField(default='', max_length=255)),
                ('parent_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subline', to='products.line')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SizeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SizeTranslationRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US', models.CharField(blank=True, max_length=16, null=True)),
                ('UK', models.CharField(blank=True, max_length=16, null=True)),
                ('EU', models.CharField(blank=True, max_length=16, null=True)),
                ('RU', models.CharField(blank=True, max_length=16, null=True)),
                ('CM', models.CharField(blank=True, max_length=16, null=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.sizetable')),
            ],
        ),
        migrations.AddField(
            model_name='sizetable',
            name='size_row',
            field=models.ManyToManyField(blank=True, null=True, related_name='rows', to='products.sizetranslationrows'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=255)),
                ('colorway', models.CharField(blank=True, max_length=255)),
                ('russian_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('manufacturer_sku', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_custom', models.BooleanField(default=False)),
                ('is_collab', models.BooleanField(default=False)),
                ('designer_color', models.SlugField(blank=True, max_length=255)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('available_flag', models.BooleanField(default=True)),
                ('has_many_sizes', models.BooleanField(default=False)),
                ('has_many_colors', models.BooleanField(default=False)),
                ('has_many_configurations', models.BooleanField(default=False)),
                ('last_upd', models.DateTimeField(default=django.utils.timezone.now)),
                ('add_date', models.DateField(default=datetime.date.today)),
                ('exact_date', models.DateField(blank=True, default=datetime.date.today)),
                ('approximate_date', models.CharField(blank=True, default='', max_length=63)),
                ('fit', models.IntegerField(default=0)),
                ('rel_num', models.IntegerField(default=0)),
                ('platform_info', models.JSONField(blank=True, null=True)),
                ('brands', models.ManyToManyField(blank=True, related_name='products', to='products.brand')),
                ('bucket_link', models.ManyToManyField(blank=True, null=True, related_name='product', to='products.photo')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='products.category')),
                ('collab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.collab')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='products.color')),
                ('gender', models.ManyToManyField(blank=True, related_name='products', to='products.gender')),
                ('lines', models.ManyToManyField(blank=True, related_name='products', to='products.line')),
                ('main_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_main', to='products.color')),
                ('main_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_products', to='products.line')),
                ('recommended_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.gender')),
                ('size_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.sizetable')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='products.tag')),
            ],
        ),
    ]
