# Generated by Django 4.1.7 on 2023-07-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_productunit_good_size_platform_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizetable',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sizetable',
            name='size_row',
        ),
        migrations.AddField(
            model_name='product',
            name='size_table_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_platform', to='products.sizetable'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sizetable',
            name='filter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sizetable',
            name='size_rows',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sizetable',
            name='standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.sizetable'),
        ),
        migrations.RemoveField(
            model_name='sizetable',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sizetable',
            name='gender',
        ),
        migrations.DeleteModel(
            name='SizeTranslationRows',
        ),
        migrations.AddField(
            model_name='sizetable',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='size_tables', to='products.category'),
        ),
        migrations.AddField(
            model_name='sizetable',
            name='gender',
            field=models.ManyToManyField(blank=True, related_name='size_tables', to='products.gender'),
        ),
    ]
