# Generated by Django 4.1.7 on 2023-06-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=127)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='bucket_link',
        ),
        migrations.AddField(
            model_name='product',
            name='bucket_link',
            field=models.ManyToManyField(blank=True, related_name='product', to='products.photo'),
        ),
    ]
