# Generated by Django 4.1.7 on 2023-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_photo_remove_product_bucket_link_product_bucket_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='release_date',
            new_name='exact_date',
        ),
        migrations.AddField(
            model_name='product',
            name='approximate_date',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='product',
            name='bucket_link',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='products.photo'),
        ),
    ]
