# Generated by Django 4.1.7 on 2023-07-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_sizetable_brand_remove_sizetable_size_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes_prices',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
