# Generated by Django 4.1.7 on 2023-06-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_line_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_main_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main', to='products.color'),
        ),
    ]
