# Generated by Django 4.1.7 on 2023-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_is_main_color_alter_product_main_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='eng_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
