# Generated by Django 4.1.7 on 2023-07-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sizes_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_flag',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_collab',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='lines',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
