# Generated by Django 4.1.7 on 2023-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='line',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
