# Generated by Django 4.1.7 on 2023-06-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_full_name_line_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_categories',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcat', to='products.category'),
        ),
    ]
