# Generated by Django 4.1.7 on 2023-07-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_available_flag_alter_product_brands_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeTranslationRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.JSONField(blank=True, null=True)),
                ('is_one_size', models.BooleanField(default=False)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='products.sizetable')),
            ],
        ),
    ]
