# Generated by Django 4.1.7 on 2023-08-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sizetranslationrows'),
    ]

    operations = [
        migrations.CreateModel(
            name='DewuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_id', models.IntegerField(default=0)),
                ('api_data', models.JSONField(default=dict)),
                ('preprocessed_data', models.JSONField(default=dict)),
                ('web_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='spu_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='dewu_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.dewuinfo'),
        ),
    ]
