# Generated by Django 4.1.7 on 2023-06-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_parent_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='full_eng_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='products.category'),
        ),
        migrations.AlterField(
            model_name='line',
            name='parent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subline', to='products.line'),
        ),
    ]
