# Generated by Django 4.1.7 on 2023-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_line_full_eng_name_alter_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='color',
            name='russian_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
