# Generated by Django 4.1.7 on 2023-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_dewuinfo_product_spu_id_product_dewu_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(default='', max_length=128)),
                ('filter_logo', models.CharField(default='', max_length=128)),
                ('sizes', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='sizetable',
            name='size_rows',
        ),
        migrations.AddField(
            model_name='sizetable',
            name='size_rows',
            field=models.ManyToManyField(blank=True, related_name='size_tables', to='products.sizerow'),
        ),
    ]
