# Generated by Django 4.1.7 on 2023-08-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_sizetable_default_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('text', models.CharField(default='', max_length=1024)),
                ('font_color', models.CharField(default='', max_length=512)),
                ('background_color', models.CharField(default='', max_length=512)),
                ('button', models.BooleanField(default=False)),
                ('button_text', models.CharField(default='', max_length=256)),
                ('categories', models.ManyToManyField(blank=True, related_name='headers', to='products.category')),
                ('genders', models.ManyToManyField(blank=True, related_name='headers', to='products.gender')),
                ('lines', models.ManyToManyField(blank=True, related_name='headers', to='products.line')),
                ('photos', models.ManyToManyField(blank=True, related_name='headers', to='products.photo')),
            ],
        ),
    ]
