# Generated by Django 4.1.7 on 2023-08-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_headerpage_photos_headerpage_photos_pc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=64)),
                ('categories', models.ManyToManyField(blank=True, related_name='headers_photos', to='products.category')),
                ('collabs', models.ManyToManyField(related_name='headers_photos', to='products.collab')),
                ('genders', models.ManyToManyField(blank=True, related_name='headers_photos', to='products.gender')),
                ('lines', models.ManyToManyField(blank=True, related_name='headers_photos', to='products.line')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='headers_photos', to='products.photo')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('text', models.CharField(default='', max_length=1024)),
                ('categories', models.ManyToManyField(blank=True, related_name='headers_text', to='products.category')),
                ('collabs', models.ManyToManyField(related_name='headers_text', to='products.collab')),
                ('genders', models.ManyToManyField(blank=True, related_name='headers_text', to='products.gender')),
                ('lines', models.ManyToManyField(blank=True, related_name='headers_text', to='products.line')),
            ],
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='button',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='font_color',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='photos_pc',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='photos_phone',
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='collab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.collab'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_main', to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_products', to='products.line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.sizetable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_table_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_platform', to='products.sizetable'),
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='', max_length=64)),
                ('photos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.headerphotos')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.headertext')),
            ],
        ),
        migrations.AddField(
            model_name='headerpage',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.headerphotos'),
        ),
        migrations.AlterField(
            model_name='headerpage',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.headertext'),
        ),
    ]
