# Generated by Django 4.1.7 on 2023-08-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_headerphotos_headertext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=64)),
                ('where', models.CharField(default='', max_length=64)),
                ('categories', models.ManyToManyField(blank=True, related_name='headers_photos', to='products.category')),
                ('collabs', models.ManyToManyField(related_name='headers_photos', to='products.collab')),
                ('genders', models.ManyToManyField(blank=True, related_name='headers_photos', to='products.gender')),
                ('lines', models.ManyToManyField(blank=True, related_name='headers_photos', to='products.line')),
                ('photo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='headers_photo', to='products.photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='headerpage',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='photos',
        ),
        migrations.DeleteModel(
            name='HeaderPhotos',
        ),
        migrations.AddField(
            model_name='headerpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.headerphoto'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.headerphoto'),
        ),
    ]
