# Generated by Django 4.1.7 on 2023-08-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_headerphoto_remove_headerpage_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerphoto',
            name='collabs',
            field=models.ManyToManyField(blank=True, related_name='headers_photos', to='products.collab'),
        ),
        migrations.AlterField(
            model_name='headertext',
            name='collabs',
            field=models.ManyToManyField(blank=True, related_name='headers_text', to='products.collab'),
        ),
    ]
