# Generated by Django 4.1.7 on 2023-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_headertext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.color'),
        ),
    ]
