# Generated by Django 4.1.7 on 2023-08-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dewu_info',
        ),
    ]
