# Generated by Django 4.1.7 on 2023-08-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_bucket_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
