# Generated by Django 4.1.7 on 2023-08-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_sginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dewuinfo',
            name='spu_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
