# Generated by Django 4.1.7 on 2023-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_material_product_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='property_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
