# Generated by Django 4.1.7 on 2023-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='another_configuration',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='similar_product',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
