# Generated by Django 4.1.7 on 2023-09-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_sizetranslationrows_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_table_platform',
        ),
        migrations.AddField(
            model_name='dewuinfo',
            name='processed_data',
            field=models.JSONField(default=dict),
        ),
    ]
