# Generated by Django 4.1.7 on 2023-09-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_size_table_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_table_platform',
            field=models.JSONField(default=dict),
        ),
    ]
