# Generated by Django 4.1.7 on 2023-09-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_product_main_size_row_product_main_size_row_of_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerphoto',
            name='photo',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
