# Generated by Django 4.1.7 on 2023-09-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_product_products_pr_id_b46934_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_id_b46934_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_spu_id_f4ec58_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_model_268e30_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_colorwa_e9728c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_slug_3edc0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_manufac_be8e97_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_cust_9419ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_coll_001e82_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_min_pri_3029f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_rel_num_530f30_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_availab_aa08f7_idx',
        ),
    ]
