# Generated by Django 4.1.7 on 2023-09-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_product_products_pr_id_b46934_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
