# Generated by Django 4.1.7 on 2023-09-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_product_min_price_without_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
