# Generated by Django 4.1.7 on 2023-09-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_product_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_sg',
            field=models.BooleanField(default=False),
        ),
    ]
