# Generated by Django 4.1.7 on 2023-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_product_actual_price_alter_product_bucket_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
