# Generated by Django 4.1.7 on 2023-09-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_product_max_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='black_bucket_link',
            field=models.ManyToManyField(blank=True, related_name='black_product', to='products.photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='designer_color',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_size_row',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_sku',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='russian_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_common_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
