# Generated by Django 4.1.7 on 2023-09-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_product_black_bucket_link_alter_product_actual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='one_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
