# Generated by Django 4.1.7 on 2023-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_product_one_update_alter_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parse_price',
            field=models.BooleanField(default=False),
        ),
    ]
