# Generated by Django 4.1.7 on 2023-09-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_product_content_sources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_common_name',
            new_name='extra_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='main_size_row',
            new_name='size_row_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_size_row_of_unit',
        ),
    ]
