# Generated by Django 4.1.7 on 2023-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_rename_unit_common_name_product_extra_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='level1_category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='level2_category_id',
            field=models.IntegerField(default=0),
        ),
    ]
