# Generated by Django 4.1.7 on 2023-10-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_alter_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.color'),
        ),
    ]
