# Generated by Django 4.1.7 on 2023-10-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_color_name_alter_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='eng_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='collab',
            name='query_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], max_length=255),
        ),
        migrations.AlterField(
            model_name='line',
            name='full_eng_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
