# Generated by Django 4.1.7 on 2023-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_alter_category_eng_name_alter_collab_query_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], db_index=True, max_length=255),
        ),
    ]
