# Generated by Django 4.1.7 on 2023-10-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_alter_sizetranslationrows_is_one_size'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_id_b46934_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_spu_id_f4ec58_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_model_268e30_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_colorwa_e9728c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_slug_3edc0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_manufac_be8e97_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_cust_9419ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_coll_001e82_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_min_pri_3029f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_rel_num_530f30_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_availab_aa08f7_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='eng_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='collab',
            name='query_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('K', 'Kids')], max_length=255),
        ),
        migrations.AlterField(
            model_name='line',
            name='full_eng_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bucket_link',
            field=models.ManyToManyField(blank=True, related_name='product', to='products.photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorway',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='formatted_manufacturer_sku',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_collab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rel_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='spu_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizetranslationrows',
            name='is_one_size',
            field=models.BooleanField(default=False),
        ),
    ]
