# Generated by Django 4.1.7 on 2023-10-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_remove_product_products_pr_id_b46934_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rel_num',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
