# Generated by Django 4.1.7 on 2023-10-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_alter_product_rel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
