# Generated by Django 4.1.7 on 2023-10-20 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_alter_product_gender_alter_product_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='exact_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_sg',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='spu_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
