# Generated by Django 4.1.7 on 2023-10-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_alter_product_available_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lines',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='products', to='products.material'),
        ),
    ]
