# Generated by Django 4.1.7 on 2023-10-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_alter_product_categories_alter_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='full_eng_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
