# Generated by Django 4.1.7 on 2023-10-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0079_remove_product_products_pr_id_b46934_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sginfo',
            name='novelty_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sginfo',
            name='relevant_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizetranslationrows',
            name='is_one_size',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='sizetranslationrows',
            index=models.Index(fields=['id'], name='products_si_id_a89b64_idx'),
        ),
        migrations.AddIndex(
            model_name='sizetranslationrows',
            index=models.Index(fields=['is_one_size'], name='products_si_is_one__71f85e_idx'),
        ),
    ]
