# Generated by Django 4.1.7 on 2023-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_sginfo_novelty_number_sginfo_relevant_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collab',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='line',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
