# Generated by Django 4.1.7 on 2023-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_brand_score_category_score_collab_score_line_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
