# Generated by Django 4.1.7 on 2023-10-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0082_alter_line_name_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizetable',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
