# Generated by Django 4.1.7 on 2023-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_rename_score_product_score_product_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes_month',
            field=models.IntegerField(default=0),
        ),
    ]
