# Generated by Django 4.1.7 on 2023-10-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0086_product_likes_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalize_rel_num',
            field=models.IntegerField(default=0),
        ),
    ]
