# Generated by Django 4.1.7 on 2023-11-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_product_normalize_rel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='likes_week',
            field=models.IntegerField(default=0),
        ),
    ]
