# Generated by Django 4.1.7 on 2023-11-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_product_extra_score_product_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
