# Generated by Django 4.1.7 on 2023-11-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0089_alter_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='up_score',
            field=models.BooleanField(default=False),
        ),
    ]
