# Generated by Django 4.1.7 on 2023-11-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_alter_product_score_product_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_recommend',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
