# Generated by Django 4.1.7 on 2023-11-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0093_product_is_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, db_index=True, default=None, related_name='products', to='products.sizetranslationrows'),
        ),
    ]
