# Generated by Django 4.1.7 on 2023-11-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertext',
            name='type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
