# Generated by Django 4.1.7 on 2023-11-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_headertext_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_process_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ransomrequest',
            name='photo',
            field=models.CharField(default='', max_length=512),
        ),
    ]
