# Generated by Django 4.1.7 on 2023-11-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0096_product_in_process_update_alter_ransomrequest_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_absolute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
