# Generated by Django 4.1.7 on 2023-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0097_product_sale_absolute_product_sale_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='order',
            field=models.IntegerField(default=1000),
        ),
    ]
