# Generated by Django 4.1.7 on 2023-12-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0098_collab_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='percentage_sale',
        ),
    ]
