# Generated by Django 4.1.7 on 2024-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0099_remove_product_percentage_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_collab',
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.collection'),
        ),
    ]
