# Generated by Django 4.1.7 on 2024-02-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0101_collection_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='subtitle',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
