# Generated by Django 4.1.7 on 2024-04-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0102_alter_collection_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_search',
            field=models.BooleanField(default=False),
        ),
    ]
