# Generated by Django 4.1.7 on 2024-04-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0103_product_in_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=512)),
                ('text', models.CharField(default='', max_length=16096)),
                ('type', models.CharField(default='', max_length=64)),
                ('categories', models.ManyToManyField(blank=True, related_name='footer_text', to='products.category')),
                ('collabs', models.ManyToManyField(blank=True, related_name='footer_text', to='products.collab')),
                ('genders', models.ManyToManyField(blank=True, related_name='footer_text', to='products.gender')),
                ('lines', models.ManyToManyField(blank=True, related_name='footer_text', to='products.line')),
            ],
        ),
    ]
