# Generated by Django 4.1.7 on 2024-06-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0104_footertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
