# Generated by Django 4.1.7 on 2024-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0105_alter_product_available_flag_alter_product_is_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='formatted_manufacturer_sku',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_sku',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
